import Head from "next/head";
import { useEffect, useState } from "react";
import { AboutPage, Experience } from "../components";
import { BsFillMoonStarsFill, BsFillCloudDownloadFill } from "react-icons/bs";
import { Portfolio } from "../components/portfolio";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    const setTheme = () => {
        const time = new Date().getHours();
        if (time >= 18) {
            setDarkMode(true);
        }
    };
    useEffect(() => {
        setTheme();
    }, []);
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Leonardo Ramirez - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between dark:text-white">
                        <h1 className="text-xl font-burtons">leoramirez</h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="cursor-pointer"
                                />
                            </li>
                            <li>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                    href="https://multilimp.s3.amazonaws.com/Resume-LeonardoRamirez.pdf"
                                    target={"_blank"}
                                    rel="noreferrer"
                                    download="Resume-LeonardoRamirez.pdf"
                                >
                                    Resume
                                    <BsFillCloudDownloadFill className="inline-block ml-2" />
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <AboutPage />
                </section>
                <Experience />
                <Portfolio />
            </main>
        </div>
    );
}
